//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        internal static string BanTitle {
            get {
                return ResourceManager.GetString("BanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions disabled.
        /// </summary>
        internal static string blockedactions {
            get {
                return ResourceManager.GetString("blockedactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EnableTitle {
            get {
                return ResourceManager.GetString("EnableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t found any data in the Database!.
        /// </summary>
        internal static string error_nodataindb {
            get {
                return ResourceManager.GetString("error_nodataindb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page.
        /// </summary>
        internal static string error_page_title {
            get {
                return ResourceManager.GetString("error_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string herarchy {
            get {
                return ResourceManager.GetString("herarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various pages.
        /// </summary>
        internal static string L_Multi {
            get {
                return ResourceManager.GetString("L_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique page.
        /// </summary>
        internal static string L_Single {
            get {
                return ResourceManager.GetString("L_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string modADM {
            get {
                return ResourceManager.GetString("modADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletins and Forecasts.
        /// </summary>
        internal static string modBFO {
            get {
                return ResourceManager.GetString("modBFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        internal static string modDBS {
            get {
                return ResourceManager.GetString("modDBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Warnings.
        /// </summary>
        internal static string modEWA {
            get {
                return ResourceManager.GetString("modEWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports &amp; Graphs.
        /// </summary>
        internal static string modGHR {
            get {
                return ResourceManager.GetString("modGHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated Pest Management.
        /// </summary>
        internal static string modIPM {
            get {
                return ResourceManager.GetString("modIPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string modMAP {
            get {
                return ResourceManager.GetString("modMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Data.
        /// </summary>
        internal static string modMET {
            get {
                return ResourceManager.GetString("modMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        internal static string modPRM {
            get {
                return ResourceManager.GetString("modPRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Documents.
        /// </summary>
        internal static string modSDO {
            get {
                return ResourceManager.GetString("modSDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turtle Nest Statistical System.
        /// </summary>
        internal static string modSET {
            get {
                return ResourceManager.GetString("modSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this section!.
        /// </summary>
        internal static string noaccess {
            get {
                return ResourceManager.GetString("noaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswdTitle {
            get {
                return ResourceManager.GetString("PasswdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to first page.
        /// </summary>
        internal static string tpl_gotofirst {
            get {
                return ResourceManager.GetString("tpl_gotofirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to last page.
        /// </summary>
        internal static string tpl_gotolast {
            get {
                return ResourceManager.GetString("tpl_gotolast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string tpl_next {
            get {
                return ResourceManager.GetString("tpl_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string tpl_previous {
            get {
                return ResourceManager.GetString("tpl_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban.
        /// </summary>
        internal static string UnbanTitle {
            get {
                return ResourceManager.GetString("UnbanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string useropSecurity {
            get {
                return ResourceManager.GetString("useropSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Settings.
        /// </summary>
        internal static string useropSettings {
            get {
                return ResourceManager.GetString("useropSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Options.
        /// </summary>
        internal static string useropTit {
            get {
                return ResourceManager.GetString("useropTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Agripanda..
        /// </summary>
        internal static string welcomeIntro {
            get {
                return ResourceManager.GetString("welcomeIntro", resourceCulture);
            }
        }
    }
}
