//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class posts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal posts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.posts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Post.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No Post ID has found.
        /// </summary>
        internal static string ErrorNoPID {
            get {
                return ResourceManager.GetString("ErrorNoPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all categories for this section.
        /// </summary>
        internal static string postCategoriesPageDesc {
            get {
                return ResourceManager.GetString("postCategoriesPageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show categories.
        /// </summary>
        internal static string postCategoriesPageTitle {
            get {
                return ResourceManager.GetString("postCategoriesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string PostCatID {
            get {
                return ResourceManager.GetString("PostCatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string PostDate {
            get {
                return ResourceManager.GetString("PostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: &lt;h6&gt;You can copy and paste text from word, excel, etc.&lt;/h6&gt;.
        /// </summary>
        internal static string postdesc {
            get {
                return ResourceManager.GetString("postdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post type:.
        /// </summary>
        internal static string PostRadioOptions {
            get {
                return ResourceManager.GetString("PostRadioOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or link:&lt;/br&gt;&lt;h6&gt;(Write a brief descripion of the document or the URL to an external link)&lt;/h6&gt;.
        /// </summary>
        internal static string PostTextDesc {
            get {
                return ResourceManager.GetString("PostTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or description.
        /// </summary>
        internal static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or title:.
        /// </summary>
        internal static string PostTitleField {
            get {
                return ResourceManager.GetString("PostTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External URL.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: &lt;h6&gt;Ex. http://www.agripanda.com/default.aspx&lt;/h6&gt;.
        /// </summary>
        internal static string urldesc {
            get {
                return ResourceManager.GetString("urldesc", resourceCulture);
            }
        }
    }
}
