//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.config", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\InetPub\vhosts\agripanda.com\httpdocs\.
        /// </summary>
        internal static string AccessPath {
            get {
                return ResourceManager.GetString("AccessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string addUPIisActive {
            get {
                return ResourceManager.GetString("addUPIisActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwf2016.
        /// </summary>
        internal static string addUPIPasswd {
            get {
                return ResourceManager.GetString("addUPIPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.wwf-mar.org:8080/.
        /// </summary>
        internal static string addUPIServer {
            get {
                return ResourceManager.GetString("addUPIServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addupi.
        /// </summary>
        internal static string addUPIUser {
            get {
                return ResourceManager.GetString("addUPIUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string CartoLeaflet {
            get {
                return ResourceManager.GetString("CartoLeaflet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; 2018, AgriPanda v2.1.1 - WWF.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/.
        /// </summary>
        internal static string ImagesDIR {
            get {
                return ResourceManager.GetString("ImagesDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.agripanda.com.
        /// </summary>
        internal static string MainURL {
            get {
                return ResourceManager.GetString("MainURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\InetPub\vhosts\agripanda.com\httpdocs\a2a\.
        /// </summary>
        internal static string PathtoA2AFiles {
            get {
                return ResourceManager.GetString("PathtoA2AFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\InetPub\vhosts\agripanda.com\httpdocs\System_Vars\.
        /// </summary>
        internal static string PathtoSystemVars {
            get {
                return ResourceManager.GetString("PathtoSystemVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipm_sigatoka_weather.
        /// </summary>
        internal static string SigatokaWSTable {
            get {
                return ResourceManager.GetString("SigatokaWSTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US:English;es-HN:Español.
        /// </summary>
        internal static string SystemLanguages {
            get {
                return ResourceManager.GetString("SystemLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:URL;2:Scheduler;3:Form;4:Grid;5:Chart;6:Gantt.
        /// </summary>
        internal static string SystemModTypes {
            get {
                return ResourceManager.GetString("SystemModTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skyblue:Sky Blue;web:Bright Blue Web;terrace:Terrace Gray;autumn:Autumn.
        /// </summary>
        internal static string SystemSkins {
            get {
                return ResourceManager.GetString("SystemSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /uploads/.
        /// </summary>
        internal static string UploadsDIR {
            get {
                return ResourceManager.GetString("UploadsDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string UseBinaryFiles {
            get {
                return ResourceManager.GetString("UseBinaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string WebSiteURL {
            get {
                return ResourceManager.GetString("WebSiteURL", resourceCulture);
            }
        }
    }
}
