//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.queries", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM contractors.
        /// </summary>
        internal static string ContractorsCountQuery {
            get {
                return ResourceManager.GetString("ContractorsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM crops.
        /// </summary>
        internal static string CropCountQuery {
            get {
                return ResourceManager.GetString("CropCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM crops ORDER BY CropID ASC.
        /// </summary>
        internal static string CropIDQuery {
            get {
                return ResourceManager.GetString("CropIDQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_deseases.
        /// </summary>
        internal static string DeseasesCountQuery {
            get {
                return ResourceManager.GetString("DeseasesCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM farms ORDER BY FarmID ASC.
        /// </summary>
        internal static string FarmQuery {
            get {
                return ResourceManager.GetString("FarmQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM farms.
        /// </summary>
        internal static string FarmsCountQuery {
            get {
                return ResourceManager.GetString("FarmsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM farms WHERE HasModel=1 ORDER BY FarmID ASC.
        /// </summary>
        internal static string FarmsRelQuery {
            get {
                return ResourceManager.GetString("FarmsRelQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM menus ORDER BY MenuID ASC.
        /// </summary>
        internal static string GetMenusQuery {
            get {
                return ResourceManager.GetString("GetMenusQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_insects.
        /// </summary>
        internal static string InsectsCountQuery {
            get {
                return ResourceManager.GetString("InsectsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM lots.
        /// </summary>
        internal static string LotsCountQuery {
            get {
                return ResourceManager.GetString("LotsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM lots ORDER BY LotID ASC.
        /// </summary>
        internal static string LotsQuery {
            get {
                return ResourceManager.GetString("LotsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_sigatoka_matrices.
        /// </summary>
        internal static string MatrixCountQuery {
            get {
                return ResourceManager.GetString("MatrixCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_models.
        /// </summary>
        internal static string ModelCountQuery {
            get {
                return ResourceManager.GetString("ModelCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM modules ORDER BY ModID ASC.
        /// </summary>
        internal static string ModulesQuery {
            get {
                return ResourceManager.GetString("ModulesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM groups.
        /// </summary>
        internal static string PmasksCountQuery {
            get {
                return ResourceManager.GetString("PmasksCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_rodents.
        /// </summary>
        internal static string RodentsCountQuery {
            get {
                return ResourceManager.GetString("RodentsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM weather_sensors ORDER BY SensorID ASC.
        /// </summary>
        internal static string SensorQuery {
            get {
                return ResourceManager.GetString("SensorQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ipm_sigatoka_matrices ORDER BY MatrixID ASC.
        /// </summary>
        internal static string SIGMATQuery {
            get {
                return ResourceManager.GetString("SIGMATQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_sigatoka_matrix_values.
        /// </summary>
        internal static string SMVCountQuery {
            get {
                return ResourceManager.GetString("SMVCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM system_vars.
        /// </summary>
        internal static string SVCountQuery {
            get {
                return ResourceManager.GetString("SVCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM users.
        /// </summary>
        internal static string UserCountQuery {
            get {
                return ResourceManager.GetString("UserCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM user_type.
        /// </summary>
        internal static string UserCountTypeQuery {
            get {
                return ResourceManager.GetString("UserCountTypeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM groups ORDER BY GroupID ASC.
        /// </summary>
        internal static string UserTypeQuery {
            get {
                return ResourceManager.GetString("UserTypeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM varieties ORDER BY VarID ASC.
        /// </summary>
        internal static string VarietiesQuery {
            get {
                return ResourceManager.GetString("VarietiesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM varieties.
        /// </summary>
        internal static string VarsCountQuery {
            get {
                return ResourceManager.GetString("VarsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM ipm_weeds.
        /// </summary>
        internal static string WeedsCountQuery {
            get {
                return ResourceManager.GetString("WeedsCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) as count FROM weather.
        /// </summary>
        internal static string WSCountQuery {
            get {
                return ResourceManager.GetString("WSCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM weather ORDER BY WSID ASC.
        /// </summary>
        internal static string WSQuery {
            get {
                return ResourceManager.GetString("WSQuery", resourceCulture);
            }
        }
    }
}
